#!/bin/bash
# Delegate script to print out the XML status report from MythTV.

# Find MythTV
mythhost=$(gawk -F '[><]' '/DBHostName/ { print $3; }' $HOME/.mythtv/config.xml)
[ ! -z "$mythhost" ]  ||  exit 1

# Connect & request
exec 3<> /dev/tcp/$mythhost/6544  || exit 2
echo -ne "GET /xml\r\n\r\n" 1>&3  || exit 3

# Read answer
answer=''
had_header=0
done_header=0
while read -u 3 -t 4 line;  do
    # Remove CRs
    line=$(echo $line | tr -d '\r')
    # Skip header
    if [ "$done_header" -eq 1 ];  then
        # A line we want
        answer="$answer$line\n"
    elif [ "$had_header" -eq 1  -a  -z "$line" ];  then
        # End of header
        done_header=1
    elif [ "$had_header" -eq 0  -a  ! -z "$line" ];  then
        # In header
        had_header=1
    fi
done

# Done
exec 3<&-
echo -en $answer
